name: "BACK: Gerenciador de Investimentos DEPLOY"

on:
  pull_request:
    branches: ["master", develop]
    paths: ["gerenciador-investimentos/**"]

jobs:
  deploy-verification:
    name: Deploy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gerenciador-investimento-app"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "gerenciador-investimentos"
