name: "BACK: Gerenciador de Investimentos DEPLOY"

on:
  pull_request:
    branches: [master, develop]
  # paths: ["gerenciador-investimentos/**"] deploy

jobs:
  verify-and-deploy:
    name: verify and deploy to heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify
        working-directory: ./gerenciador-investimentos
        run: mvn verify
      - name: deploy to heroku
        run: git subtree --prefix gerenciador-investimentos push --force https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/gerenciador-investimento-app.git HEAD:main
