name: "BACK: Gerenciador de Investimentos DEPLOY"

on:
  pull_request:
    branches: [master, develop]
  # paths: ["gerenciador-investimentos/**"] deploy

jobs:
  deploy-verification:
    name: Deploy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: check
        working-directory: ./gerenciador-investimentos
        env:
          GERENCIADOR-INVESTIMENTO_SECURITY_SECRET: ${{secrets.TOKENSIGNINGKEY}}
        run: mvn verify
      - name: heroku login
        run: heroku login
      - name: heroku deploy
        run: git push ${{secrets.HEROKU_BRANCH}} develop
        working-directory: ./gerenciador-investimentos
