name: "BACK: Gerenciador de Investimentos DEPLOY"

on:
  pull_request:
    branches: [master, develop]
    paths: ["gerenciador-investimentos/**"]

jobs:
  deploy-verification:
    name: Deploy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: check
        working-directory: ./gerenciador-investimentos
        env:
          GERENCIADOR-INVESTIMENTO_SECURITY_SECRET: ${{secrets.TOKENSIGNINGKEY}}
        run: mvn verify
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gerenciador-investimento-app"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "gerenciador-investimentos/"
          remote_branch: ${{secrest.HEROKU_BRANCH}}
