name: "BACK: Gerenciador de Investimentos DEPLOY"

on:
  push:
    branches: [master]
    paths: ["gerenciador-investimentos/**"]
  pull_request:
    branches: [develop]
    paths: ["gerenciador-investimentos/**"]

jobs:
  verify-and-deploy:
    name: verify and deploy to heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify
        working-directory: ./gerenciador-investimentos
        run: mvn verify
      - name: deploy to heroku
        run: git push https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/gerenciador-investimento-app.git `git subtree split --prefix gerenciador-investimentos HEAD`:main --force
