name: "BACK: Gerenciador de Investimentos DEPLOY"

on:
  pull_request:
    branches: [master, develop]
  # paths: ["gerenciador-investimentos/**"] deploy

jobs:
  deploy-verification:
    name: Deploy Check
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: check
        working-directory: ./gerenciador-investimentos
        env:
          GERENCIADOR-INVESTIMENTO_SECURITY_SECRET: ${{secrets.TOKENSIGNINGKEY}}
        run: mvn verify
      # - name: heroku create remote
      #   run: heroku git:remote -a gerenciador-investimento-app
      - name: heroku deploy
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/gerenciador-investimento-app.git HEAD:main
        working-directory: ./gerenciador-investimentos
